[package]
name = "dezoomify-rs"
version = "0.1.0"
authors = ["Ophir LOJKINE <ophir.lojkine@auto-grid.com>"]
edition = "2018"

[dependencies]
image = "0.21.1"
reqwest = "0.9.14"
custom_error = "1.6.0"
structopt = "0.2"