[package]
name = "dezoomify-rs"
version = "1.5.0"
authors = ["Ophir LOJKINE <ophir.lojkine@auto-grid.com>"]
edition = "2018"
license-file = "LICENSE"

[dependencies]
image = "0.22.1"
reqwest = "0.9"
custom_error = "1.7.1"
structopt = "0.2"
evalexpr = "4.1"
regex = "1"
lazy_static = "1.3"
itertools = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
serde-xml-rs = "0.3"
serde_json = "1.0"
rayon = "1.1"
block-modes = "0.3"
aes = "0.3"
hmac = "0.7"
sha-1 = "0.8"
base64 = "0.10"
indicatif = "0.11"