[package]
name = "dezoomify-rs"
version = "0.6.1"
authors = ["Ophir LOJKINE <ophir.lojkine@auto-grid.com>"]
edition = "2018"
license-file = "LICENSE"

[dependencies]
image = "0.21"
reqwest = "0.9"
custom_error = "1.7.1"
structopt = "0.2"
evalexpr = "4.1"
regex = "1"
lazy_static = "1.3"
itertools = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
rayon = "1.1"
